version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        - FRONTEND-PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db:/usr/src/app/db
